CREATE TABLE RESUMES (
    ID INT PRIMARY KEY,
    NAME VARCHAR(255),
    EMAIL VARCHAR(255),
    PHONE VARCHAR(255),
    SUMMARY TEXT,
    EXPERIENCE TEXT,
    EDUCATION TEXT,
    SKILLS TEXT
);

INSERT INTO RESUMES ( ID, NAME, EMAIL, PHONE, SUMMARY, EXPERIENCE, EDUCATION, SKILLS ) VALUES ( 1, 'John Doe', ';